### ISSUE TITLE
veru goos xcoders

### ISSUE THREAD

**Issue by amplitudesxd** [capybarasoln/badcode#2]
veri go0d codar 10/7 👌 👍 👏 😀 😎 🙌

**Comment by forageddev** [comment]
who the fuck asked?

**Comment by GrowlyX** [comment]
> who the fuck asked?

Please be nice to our members, or you will be kicked

**Comment by forageddev** [comment]
who asked you?

**Comment by forageddev** [comment]
WAIT WHAT THE FUCK HOW CAN YOU EDIT MY SHIT

**Comment by forageddev** [comment]
THAT SHIT IS FUCKKKED LLOL

**Comment by ItzBunniYT** [comment]
> i skid lol

bro where

**Comment by ItzBunniYT** [comment]
hey gamers
