### ISSUE TITLE
> who the fuck asked?

### ISSUE THREAD

**Issue by forageddev** [capybarasoln/badcode#3]
> who the fuck asked?

Please be nice to our members, or you will be kicked

_Originally posted by @GrowlyX in https://github.com/capybarasoln/badcode/issues/2#issuecomment-1023433805_

**Comment by forageddev** [comment]
twat

**Comment by GrowlyX** [comment]
??

**Comment by forageddev** [comment]
why are you so active you wierd child.

**Comment by forageddev** [comment]
rgf
er
ger
g
erg
erg

**Comment by forageddev** [comment]
g

**Comment by forageddev** [comment]
g

**Comment by forageddev** [comment]
g

**Comment by forageddev** [comment]
g

**Comment by forageddev** [comment]
g

**Comment by ItzBunniYT** [comment]
fuck you im closing this issue.

Issue Fixed.

How to fix: Simply die.
